### ISSUE TITLE
New Hotwords

### ISSUE THREAD

**Issue by lawrencenull** [jaxcore/bumblebee-hotword#3]
Any chance of having the new Hotwords added that have been open sourced?

1. Alexa
2. Jarvis
3. Computer
4. Mirror

etc

**Comment by dsteinman** [comment]
Yeah it's easy to add more words. Do you know where the PPN files for the new words are?  I don't see any new ones in Picovoice repo:

https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files

**Comment by dsteinman** [comment]
I see there are PPN files for those words in the porcupine repo Linux directory, but it looks like they did not create WASM versions of those words:

https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/wasm

This fork I created only uses the WASM files.

**Comment by lawrencenull** [comment]
I see, their open source license is very confusing. It seems everything in the Linux directory is open source but if you use it on the web it isn't...I think.

**Comment by lawrencenull** [comment]
Although hey Edison would be nice if you are allowed to use it. https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/wasm

**Comment by dsteinman** [comment]
When I created this fork I asked them if everything was under the Apache license and if my fork was all good and they said yes.  

Any of those WASM files should work.  I just need to convert the WASM PPN files and insert the resulting data array into the Javascript library.  But they've also changed the list of words and updated their codebase a bit.  So it might be a bit more work than just converting a file.  I'll have to get back to you when I've had a chance to look at it a bit more.

**Comment by dsteinman** [comment]
I'm taking another look at this potential upgrade, but I kinda don't want to do it.  Assuming the new WASM file format is incompatible with the version I'm using, I'd lose these 4 hotwords:

dragonfly
caterpillar
christina
francesca

And I don't gain any new ones that I'd probably ever want to use.  I'll keep this thread open as a reminder to check if they open source  some new ones (like "computer" or "operator" would be great).

**Comment by lawrencenull** [comment]
I was really hoping there would be some compatibility. Edison would have been a nice one to add. Thank you for looking into this.

**Comment by dsteinman** [comment]
On a branch I just gave it a quick try to upgrade the WASM file and unfortunately it's going to be an ugly upgrade, Porcupine have changed the wasm/javascript format more than I thought so it's not a straight swap in like I'd hoped.

So their new JavaScript library:
https://github.com/Picovoice/porcupine/blob/master/lib/wasm/pv_porcupine.js

Only works with their new wasm format:
https://github.com/Picovoice/porcupine/blob/master/lib/wasm/pv_porcupine.wasm

And I'd basically have to comb through pv_porcupine.js for the all the changes and re-apply them to the version of pv_porcupine.js that I used from several months ago.  Yeah I don't think I'm gonna do this cause that was very unpleasant on the first go around.

**Comment by dsteinman** [comment]
Just an FYI I might actually be going ahead with the upgrade mainly because as I've been testing more the number of false positives across the board is a bit too high with the older version of Porcupine.

But I'm going to go a step further and was wondering what you think about it.

I'm planning to combine Porcupine and [Mozilla DeepSpeech](https://github.com/dsteinman/DeepSpeech-examples/tree/r0.6-web-microphone-websocket/web_microphone_websocket) into a single speech project that does both hotword detection & speech recognition.  What I noticed was both Porcupine and DeepSpeech require audio processing at the exact 512 byte / 16000 sample rate, so the processing and downsampling for both tasks can be done at the same time in a background web worker task.  My plan all along has been to be able to activate and de-active DeepSpeech using BumbleBee.

The end result should be kinda like Alexa where you can say "BumbleBee" or "Hey Edison" and then DeepSpeech speech recognition will turn on and process the follow up words that are spoken.

I haven't quite decided if I'll stick to the same "bumblebee" project name or not though.

**Comment by dsteinman** [comment]
It actually turned out to be a lot simpler than I thought.  Picovoice supplied an NPM module that only needed a couple of tweaks to do what I need.  v0.0.3 is now published.
